name: Asset Management
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  
jobs:
  get-archer-shortname:
    runs-on: ubuntu-latest
    outputs:
      archershortname: "awesomeapp"
  get-tanium-data:
    needs: get-archer-shortname
    runs-on: ubuntu-latest
    env:
      taniumdata: ${{ needs.get-archer-shortname.outputs.archershortname }}
    steps:
      - name: print-tanium-data
        run: |
          echo $taniumdata  
          python myscript.py