name: Asset Management
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  
jobs:
  get-archer-shortname:
    runs-on: ubuntu-latest
    outputs:
      archershortname: "awesomeapp"
    steps:
      - id: get-shortname
        run: |
          echo "archershortname=$(echo "$title" | awk '{print $NF}')" | tee -a $GITHUB_OUTPUT
  get-tanium-data:
    needs: get-archer-shortname
    runs-on: onprem-linux
    env:
      taniumdata: ${{ needs.get-archer-shortname.outputs.archershortname }}
    steps:
      - name: print-tanium-data
        run: |
          echo $taniumdata