name: testaction
on:
  workflow_dispatch:
  
jobs:
  take_input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run actions
        run: |
          echo "Hello World"
          python myscript.py
